*: improve error messages
This switches things over to anyhow for many (but not all) of our
errors, and removes the use of unwrap from database loading.

Here's the before and after for an error opening the frecency database:

Before:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/frecent_paths.rs:43:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

After:

```
could not open pazi frecency file: "/home/user/.config/pazi/pazi_dirs.msgpack"

Caused by:
    Permission denied (os error 13)
```

I think it looks much nicer with this :)